apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${CLUSTER_NAME}
  region: ${AWS_REGION}
  version: "1.21"

availabilityZones: ["${AWS_REGION}a", "${AWS_REGION}b", "${AWS_REGION}c"]

managedNodeGroups:
- name: spot
  instanceTypes: ["t3a.medium","t3.medium","t3a.large","t3.large"]
  spot: true
  desiredCapacity: 2
  minSize: 1
  maxSize: 10

# To enable all of the control plane logs, uncomment below:
cloudWatch:
 clusterLogging:
   enableTypes: ["*"]

secretsEncryption:
  keyARN: ${MASTER_ARN}