apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${CLUSTER_NAME}
  region: ${AWS_REGION}
  version: "1.17"

availabilityZones: ["${AWS_REGION}a", "${AWS_REGION}b", "${AWS_REGION}c"]

nodeGroups:
- name: ng-1
  minSize: 2
  maxSize: 5
  ssh:
    allow: true
    publicKeyName: ${EC2_KEYPAIR}
  instancesDistribution:
    instanceTypes: ["t3.small", "t3.medium"] # At least one instance type should be specified
    onDemandBaseCapacity: 0
    onDemandPercentageAboveBaseCapacity: 50
    spotInstancePools: 2

# To enable all of the control plane logs, uncomment below:
cloudWatch:
 clusterLogging:
   enableTypes: ["*"]

secretsEncryption:
  keyARN: ${MASTER_ARN}